#include "Webserver/DisplayPage.h"
#ifdef DDC_HAS_WEBPAGE

    #include "DeviceDisplay.h"
    #include "Devices/ButtonEvent.h"
    #include "OpenKNX/Network/Module.h"
    #include "OpenKNX/Network/Webserver/Webserver.h"
    #include "ScreenshotBmp.h"
    #include "Settings/SettingsIds.h"
    #include "Widget.h"
    #include "WidgetsManager.h"
    #include "devices/i2cDisplay.h"
    #include "webassets.h" // generated by OGM-Common/scripts/pio/prepare.py from web/assets/
    #include <cstdio>
    #include <cstdlib> // malloc/free for the BMP buffer, strtol for the posted value
    #include <cstring>
    #include <string>

using namespace OpenKNX::Network;

namespace OpenKNX
{
    namespace
    {
        bool _initialized = false;

        // ── Deferred action queue ─────────────────────────────────────────────
        // Requests queue their change instead of applying it in the handler (the ESP32 httpd task would
        // race the drawing loop). Single producer (HTTP) / single consumer (KNX loop), lock-free.
        enum : uint8_t
        {
            ACT_SETTING = 0, // id + value      -> settings store
            ACT_KEY = 1,     // a=ButtonType    -> injected button event, b=ButtonAction
            ACT_WIDGET = 2   // a=op, b=index   -> widget enable/duration/move
        };

        enum : uint8_t
        {
            WOP_ENABLE = 0,
            WOP_DURATION = 1,
            WOP_MOVE = 2
        };

        struct PendingAction
        {
            uint8_t kind;
            uint8_t a;
            int16_t b;
            long value;
            char id[24]; // ACT_SETTING only
        };

        constexpr uint8_t PENDING_SLOTS = 8;
        PendingAction _pending[PENDING_SLOTS];
        volatile uint8_t _pendingHead = 0; // producer
        volatile uint8_t _pendingTail = 0; // consumer

        bool queueAction(uint8_t kind, uint8_t a, int16_t b, long value, const char* id = nullptr)
        {
            const uint8_t head = _pendingHead;
            const uint8_t next = (uint8_t)((head + 1) % PENDING_SLOTS);
            if (next == _pendingTail) return false; // queue full, caller reports "busy"

            PendingAction& slot = _pending[head];
            slot.kind = kind;
            slot.a = a;
            slot.b = b;
            slot.value = value;
            if (id != nullptr)
            {
                strncpy(slot.id, id, sizeof(slot.id) - 1);
                slot.id[sizeof(slot.id) - 1] = '\0';
            }
            else
            {
                slot.id[0] = '\0';
            }
            _pendingHead = next; // publish only after the slot is complete
            return true;
        }

        // Duration choices in seconds, identical to the on-device "Anzeigedauer" menu.
        const uint16_t WIDGET_DURATIONS[] = {5, 8, 10, 15, 20, 30};
        constexpr size_t WIDGET_DURATION_COUNT = sizeof(WIDGET_DURATIONS) / sizeof(WIDGET_DURATIONS[0]);

        // ── Framebuffer access ────────────────────────────────────────────────
        // Read while the loop may be drawing; the buffer is allocated once at begin(), so a concurrent
        // read shows at worst a torn frame, never an invalid pointer.
        const uint8_t* framebuffer(uint16_t& w, uint16_t& h, size_t& bytes)
        {
            w = h = 0;
            bytes = 0;
            i2cDisplay* display = openknxDisplayModule.getDisplayModule();
            if (display == nullptr) return nullptr;

            const uint8_t* fb = display->getFramebuffer();
            if (fb == nullptr) return nullptr;

            w = display->GetDisplayWidth();
            h = display->GetDisplayHeight();
            if (w == 0 || w > 128 || h == 0 || (w % 8) != 0) return nullptr;

            bytes = (size_t)(w / 8) * h;
            return fb;
        }

        // Fixed-capacity Print sink, so ScreenshotBmp can stream into a plain buffer.
        class BufferPrint : public Print
        {
          public:
            BufferPrint(uint8_t* buffer, size_t capacity) : _buffer(buffer), _capacity(capacity) {}

            size_t write(uint8_t b) override
            {
                if (_length >= _capacity) return 0;
                _buffer[_length++] = b;
                return 1;
            }

            size_t write(const uint8_t* data, size_t size) override
            {
                const size_t room = _capacity - _length;
                const size_t n = size < room ? size : room;
                memcpy(_buffer + _length, data, n);
                _length += n;
                return n;
            }

            size_t length() const { return _length; }

          private:
            uint8_t* _buffer;
            size_t _capacity;
            size_t _length = 0;
        };

        // ── JSON ──────────────────────────────────────────────────────────────
        // labels are fixed ASCII/UTF-8 with no quote/backslash, so plain concatenation is safe.
        std::string buildConfigJson()
        {
            std::string json("{\"settings\":[");
            json.reserve(1536);

            for (size_t i = 0; i < DISPLAY_SETTING_DEF_COUNT; ++i)
            {
                const DisplaySettingDef& def = DISPLAY_SETTING_DEFS[i];
                long value = 0;
                readDisplaySetting(def.id, value);

                char entry[224] = {};
                snprintf(entry, sizeof(entry),
                         "%s{\"id\":\"%s\",\"label\":\"%s\",\"hint\":\"%s\",\"kind\":%u,"
                         "\"min\":%ld,\"max\":%ld,\"value\":%ld",
                         i == 0 ? "" : ",", def.id, def.label, def.hint,
                         (unsigned)def.kind, def.min, def.max, value);
                json += entry;

                if (def.kind == DisplaySettingKind::Choice)
                {
                    json += ",\"options\":[";
                    for (long option = def.min; option <= def.max; ++option)
                    {
                        const char* label = displayChoiceLabel(def.id, option);
                        if (label == nullptr) break;
                        if (option > def.min) json += ",";
                        json += "\"";
                        json += label;
                        json += "\"";
                    }
                    json += "]";
                }
                json += "}";
            }

            json += "]}";
            return json;
        }

        // ── Routes ────────────────────────────────────────────────────────────
        const char dspPage[] =
            "<h1>Display <span id='dsp-status' class='dsp-status'>Lade&hellip;</span></h1>"
            "<div class='dsp-stage'>"
            "<canvas id='dsp-canvas' width='128' height='64'></canvas>"
            "</div>"
            "<div class='dsp-bar'>"
            "<label>Aktualisierung "
            "<select id='dsp-rate'>"
            "<option value='0'>aus</option>"
            "<option value='250'>4x/s</option>"
            "<option value='500' selected>2x/s</option>"
            "<option value='1000'>1x/s</option>"
            "<option value='5000'>alle 5s</option>"
            "</select></label>"
            "<button type='button' id='dsp-now'>Jetzt</button>"
            "<label><input type='checkbox' id='dsp-inv'> Invertieren</label>"
            "<a href='/display/shot.bmp' download='display.bmp'>BMP speichern</a>"
            "</div>"
            "<div class='dsp-tabs'>"
            "<a class='dsp-tab active' data-t='op'>Bedienung</a>"
            "<a class='dsp-tab' data-t='wg'>Widgets</a>"
            "<a class='dsp-tab' data-t='st'>Einstellungen</a>"
            "</div>"
            "<div id='t-op'>"
            "<div class='dsp-pad'>"
            "<button class='u' data-k='0'>&#9650;</button>"
            "<button class='l' data-k='2'>&#9664;</button>"
            "<button class='o' data-k='4'>OK</button>"
            "<button class='r' data-k='3'>&#9654;</button>"
            "<button class='d' data-k='1'>&#9660;</button>"
            "</div>"
            "<p class='meta'>Halten wirkt wie am Gerät &ndash; kurz tippen navigiert, gedrückt halten löst die Halte-Aktion aus.</p>"
            "</div>"
            "<div id='t-wg' hidden>"
            "<div id='dsp-widgets'>Lade&hellip;</div>"
            "</div>"
            "<div id='t-st' hidden>"
            "<div id='dsp-settings'>Lade&hellip;</div>"
            "<p class='meta'>&#9888; Änderungen werden sofort übernommen und gespeichert.</p>"
            "</div>";

        void handleFramebuffer(WebRequest&, WebResponse& res)
        {
            uint16_t w = 0, h = 0;
            size_t bytes = 0;
            const uint8_t* fb = framebuffer(w, h, bytes);
            if (fb == nullptr)
            {
                res.setStatus(503);
                res.setContentType("text/plain");
                res.send("no display");
                return;
            }

            char dim[16] = {};
            snprintf(dim, sizeof(dim), "%ux%u", (unsigned)w, (unsigned)h);
            res.setContentType("application/octet-stream");
            res.setHeader("X-Display-Size", dim);
            res.send(fb, (int)bytes);
        }

        void handleScreenshotBmp(WebRequest&, WebResponse& res)
        {
            uint16_t w = 0, h = 0;
            size_t bytes = 0;
            const uint8_t* fb = framebuffer(w, h, bytes);
            if (fb == nullptr)
            {
                res.setStatus(503);
                res.setContentType("text/plain");
                res.send("no display");
                return;
            }

            const size_t total = ScreenshotBmp::fileSize(w, h);
            uint8_t* buffer = (uint8_t*)malloc(total);
            if (buffer == nullptr)
            {
                res.setStatus(503);
                res.setContentType("text/plain");
                res.send("out of memory");
                return;
            }

            BufferPrint sink(buffer, total);
            ScreenshotBmp::write(sink, fb, w, h, openknxDisplayModule.settingsStore().screenshotInvert());

            res.setContentType("image/bmp");
            res.setHeader("Content-Disposition", "attachment; filename=\"display.bmp\"");
            res.send(buffer, (int)sink.length());
            free(buffer);
        }

        void handleConfigGet(WebRequest&, WebResponse& res)
        {
            res.setContentType("application/json");
            res.send(buildConfigJson().c_str());
        }

        void handleConfigPost(WebRequest& req, WebResponse& res)
        {
            res.setContentType("application/json");

            const std::string id = req.getQueryParam("id");
            const std::string value = req.getQueryParam("value");
            if (id.empty() || value.empty())
            {
                res.setStatus(400);
                res.send("{\"error\":\"id and value required\"}");
                return;
            }
            if (findDisplaySetting(id.c_str()) == nullptr)
            {
                res.setStatus(404);
                res.send("{\"error\":\"unknown id\"}");
                return;
            }

            // No std::stol: it throws, and -fno-exceptions turns that into an abort().
            char* end = nullptr;
            const long parsed = strtol(value.c_str(), &end, 10);
            if (end == value.c_str() || *end != '\0')
            {
                res.setStatus(400);
                res.send("{\"error\":\"value must be an integer\"}");
                return;
            }

            if (!queueAction(ACT_SETTING, 0, 0, parsed, id.c_str()))
            {
                res.setStatus(503);
                res.send("{\"error\":\"busy\"}");
                return;
            }

            res.send("{\"ok\":true}");
        }

        // Integer query parameter; returns `def` when absent or not a plain integer.
        long queryInt(WebRequest& req, const char* name, long def)
        {
            const std::string raw = req.getQueryParam(name);
            if (raw.empty()) return def;
            char* end = nullptr;
            const long v = strtol(raw.c_str(), &end, 10);
            return (end == raw.c_str() || *end != '\0') ? def : v;
        }

        // POST /display/key?k=<0..4>&a=<0 press|1 release|2 tap>
        // A HOLD needs press/release as separate requests (real time must pass for the gesture engine to
        // arm); a=2 taps both in one apply -> one connection instead of two (the RP2040 server has 3 slots).
        void handleKey(WebRequest& req, WebResponse& res)
        {
            res.setContentType("application/json");

            const long key = queryInt(req, "k", -1);
            const long action = queryInt(req, "a", -1);
            if (key < 0 || key > 4 || action < 0 || action > 2)
            {
                res.setStatus(400);
                res.send("{\"error\":\"k=0..4, a=0..2\"}");
                return;
            }

            if (!queueAction(ACT_KEY, (uint8_t)key, (int16_t)action, 0))
            {
                res.setStatus(503);
                res.send("{\"error\":\"busy\"}");
                return;
            }
            res.send("{\"ok\":true}");
        }

        // GET /display/widgets -> rotation order with enabled flag + duration (seconds). Short keys: polled by the page.
        void handleWidgetsGet(WebRequest&, WebResponse& res)
        {
            res.setContentType("application/json");

            WidgetsManager* wm = openknxDisplayModule.getWidgetManager();
            if (wm == nullptr)
            {
                res.send("{\"w\":[]}");
                return;
            }

            std::string json = "{\"d\":[";
            for (size_t i = 0; i < WIDGET_DURATION_COUNT; ++i)
            {
                if (i > 0) json += ",";
                json += std::to_string(WIDGET_DURATIONS[i]);
            }
            json += "],\"w\":[";

            const std::vector<Widget*> widgets = wm->getReorderableWidgets();
            for (size_t i = 0; i < widgets.size(); ++i)
            {
                Widget* widget = widgets[i];
                if (widget == nullptr) continue;

                const std::string name = widget->getName();
                const uint32_t durationMs = wm->getWidgetDisplayTime(name);

                if (i > 0) json += ",";
                json += "{\"n\":\"";
                // names come from code, but escape anyway - one stray quote would break the page.
                for (char c : name)
                {
                    if (c == '"' || c == '\\') json += '\\';
                    json += c;
                }
                json += "\",\"e\":";
                json += widget->isEnabled() ? "1" : "0";
                json += ",\"s\":";
                json += std::to_string(durationMs / 1000);
                json += "}";
            }
            json += "]}";
            res.send(json.c_str());
        }

        // POST /display/widget?i=<index>&e=<0|1> | &s=<seconds> | &m=<-1|1>   (index-based: fewer bytes than a name)
        void handleWidgetPost(WebRequest& req, WebResponse& res)
        {
            res.setContentType("application/json");

            const long index = queryInt(req, "i", -1);
            if (index < 0 || index > 255)
            {
                res.setStatus(400);
                res.send("{\"error\":\"i required\"}");
                return;
            }

            uint8_t op;
            long value;
            if (!req.getQueryParam("e").empty())
            {
                op = WOP_ENABLE;
                value = queryInt(req, "e", 1) != 0 ? 1 : 0;
            }
            else if (!req.getQueryParam("s").empty())
            {
                op = WOP_DURATION;
                value = queryInt(req, "s", 10);
            }
            else if (!req.getQueryParam("m").empty())
            {
                op = WOP_MOVE;
                value = queryInt(req, "m", 0) < 0 ? -1 : 1;
            }
            else
            {
                res.setStatus(400);
                res.send("{\"error\":\"e, s or m required\"}");
                return;
            }

            if (!queueAction(ACT_WIDGET, op, (int16_t)index, value))
            {
                res.setStatus(503);
                res.send("{\"error\":\"busy\"}");
                return;
            }
            res.send("{\"ok\":true}");
        }

        // ── Deferred appliers (loop context) ──────────────────────────────────
        void applyKey(uint8_t key, uint8_t action)
        {
            static const ButtonType TYPES[] = {
                ButtonType::UP, ButtonType::DOWN, ButtonType::LEFT,
                ButtonType::RIGHT, ButtonType::SELECT};
            if (key >= (sizeof(TYPES) / sizeof(TYPES[0]))) return;

            if (action == 2) // tap: both halves at once, no tick between them -> no gesture
            {
                openknxDisplayModule.handleButtonEvent(ButtonEvent(TYPES[key], ButtonAction::PRESS));
                openknxDisplayModule.handleButtonEvent(ButtonEvent(TYPES[key], ButtonAction::RELEASE));
                return;
            }
            if (action > 1) return;

            openknxDisplayModule.handleButtonEvent(
                ButtonEvent(TYPES[key], action == 0 ? ButtonAction::PRESS : ButtonAction::RELEASE));
        }

        bool applyWidget(uint8_t op, int16_t index, long value)
        {
            WidgetsManager* wm = openknxDisplayModule.getWidgetManager();
            if (wm == nullptr) return false;

            const std::vector<Widget*> widgets = wm->getReorderableWidgets();
            if (index < 0 || (size_t)index >= widgets.size() || widgets[index] == nullptr) return false;

            if (op == WOP_ENABLE)
            {
                widgets[index]->setEnabled(value != 0);
                return true;
            }
            if (op == WOP_DURATION)
            {
                // clamp to the offered choices so a crafted request can't park an off-menu duration.
                uint16_t seconds = WIDGET_DURATIONS[WIDGET_DURATION_COUNT - 1];
                for (size_t i = 0; i < WIDGET_DURATION_COUNT; ++i)
                    if ((long)WIDGET_DURATIONS[i] >= value) { seconds = WIDGET_DURATIONS[i]; break; }

                wm->setWidgetDisplayTime(widgets[index]->getName(), (uint32_t)seconds * 1000u);
                return true;
            }
            if (op == WOP_MOVE)
            {
                // Same grab/move/drop sequence the on-device reorder editor uses.
                if (!wm->grabWidget((size_t)index)) return false;
                const bool moved = (value < 0) ? wm->moveGrabbedUp() : wm->moveGrabbedDown();
                wm->dropWidget();
                return moved;
            }
            return false;
        }
    } // namespace

    void DisplayPage::setup()
    {
        if (_initialized) return;
        _initialized = true;

        openknxNetwork.webserver.addMenuItem("Display", "/display", 120);

        openknxNetwork.webserver.addRoute(
            WEB_GET, "/assets/display.css",
            Webserver::Asset(WebAssets::display_css_mime, WebAssets::display_css_gz, sizeof(WebAssets::display_css_gz)));
        openknxNetwork.webserver.addRoute(
            WEB_GET, "/assets/display.js",
            Webserver::Asset(WebAssets::display_js_mime, WebAssets::display_js_gz, sizeof(WebAssets::display_js_gz)));
        openknxNetwork.webserver.addStylesheet("/assets/display.css");
        openknxNetwork.webserver.addJavaScript("/assets/display.js");

        openknxNetwork.webserver.addRoute(WEB_GET, "/display", [](WebRequest&, WebResponse& res) {
            res.setContentType("text/html");
            res.setLayout(true);
            res.sendStatic(dspPage);
        });

        openknxNetwork.webserver.addRoute(WEB_GET, "/display/fb.bin", handleFramebuffer);
        openknxNetwork.webserver.addRoute(WEB_GET, "/display/shot.bmp", handleScreenshotBmp);
        openknxNetwork.webserver.addRoute(WEB_GET, "/display/config", handleConfigGet);
        openknxNetwork.webserver.addRoute(WEB_POST, "/display/config", handleConfigPost);
        openknxNetwork.webserver.addRoute(WEB_POST, "/display/key", handleKey);
        openknxNetwork.webserver.addRoute(WEB_GET, "/display/widgets", handleWidgetsGet);
        openknxNetwork.webserver.addRoute(WEB_POST, "/display/widget", handleWidgetPost);
    }

    void DisplayPage::loop()
    {
        if (_pendingTail == _pendingHead) return;

        bool settingsChanged = false;
        bool widgetsChanged = false;
        bool keyApplied = false;

        while (_pendingTail != _pendingHead)
        {
            const PendingAction& slot = _pending[_pendingTail];

            // one button event per loop pass: press+release need a tick between them for the gesture engine to arm.
            if (slot.kind == ACT_KEY && keyApplied) break;

            switch (slot.kind)
            {
                case ACT_SETTING:
                    if (applyDisplaySetting(slot.id, slot.value)) settingsChanged = true;
                    break;
                case ACT_KEY:
                    applyKey(slot.a, (uint8_t)slot.b);
                    keyApplied = true;
                    break;
                case ACT_WIDGET:
                    if (applyWidget(slot.a, slot.b, slot.value)) widgetsChanged = true;
                    break;
                default:
                    break;
            }
            _pendingTail = (uint8_t)((_pendingTail + 1) % PENDING_SLOTS);
        }

        // push live + mark dirty; the store commits to flash from its own settle timer (short loop pass).
        if (settingsChanged)
            openknxDisplayModule.webApplyAndSave();
        else if (widgetsChanged)
            openknxDisplayModule.getSettingsStore().requestSave();
    }
} // namespace OpenKNX

#endif // DDC_HAS_WEBPAGE
